### ISSUE TITLE
Midi and sync

### ISSUE THREAD

**Issue by francescortiz** [x37v/jackcpp#1]
Hi,

Are you planning to imlpement midi and sync?

Thanks

**Comment by x37v** [comment]
I'd definitely like to get sync in there, and MIDI would be nice.  I'm pretty busy right now [busy time of year for my job] so I'm not sure when I'd get to it.

If you decide to add to JackCpp, I'd certainly take a look at any pullrec you send.

**Comment by francescortiz** [comment]
That's good to read.

Right now I am busy too, and I lack C++ experience, so I don't think I can come out with something reliable before you do, but I let you know if I add any of both features.
